# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2025-10-03 19:25
from __future__ import unicode_literals

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.CharField(default=events.models.nuuid, max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=2000)),
                ('description', models.TextField()),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
