# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2025-10-03 20:28
from __future__ import unicode_literals

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventGroup',
            fields=[
                ('id', models.CharField(default=events.models.nuuid, max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=2000)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='eventgroup',
            name='events',
            field=models.ManyToManyField(to='events.Event'),
        ),
    ]
