# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2025-10-03 19:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import newspaper.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.CharField(default=newspaper.models.nuuid, max_length=200, primary_key=True, serialize=False)),
                ('in_paper_id', models.CharField(max_length=2000)),
                ('url', models.CharField(max_length=2000)),
                ('scraped', models.DateTimeField(auto_now_add=True)),
                ('published', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=2000)),
                ('content', models.TextField()),
                ('author', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Newspaper',
            fields=[
                ('id', models.CharField(default=newspaper.models.nuuid, max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=2000)),
                ('base_url', models.CharField(max_length=2000)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='newspaper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='newspaper.Newspaper'),
        ),
    ]
