# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2025-10-03 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspaper',
            name='country',
            field=models.CharField(default='it', max_length=100),
            preserve_default=False,
        ),
    ]
