# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2025-10-03 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0002_newspaper_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='media',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
