# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2025-10-04 06:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0004_auto_20251003_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewspaperSubpage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('newspaper', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pages', to='newspaper.Newspaper')),
            ],
        ),
    ]
