# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2025-10-08 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0005_newspapersubpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='archve_org',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
