# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2025-10-08 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0006_article_archve_org'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
            ],
        ),
        migrations.AddField(
            model_name='newspaper',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='newspaper.Tag'),
        ),
    ]
