# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2025-10-08 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0007_auto_20251008_0657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newspaper',
            name='country',
        ),
        migrations.AddField(
            model_name='tag',
            name='category',
            field=models.CharField(default=' ', max_length=2000),
            preserve_default=False,
        ),
    ]
