# Generated by Django 5.2.7 on 2025-10-08 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0008_auto_20251008_0658'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analyzed', models.DateTimeField(auto_now_add=True)),
                ('tool', models.CharField(max_length=2000)),
                ('model', models.CharField(max_length=2000)),
                ('analysis', models.CharField(max_length=2000)),
                ('result', models.JSONField(blank=True, null=True)),
                ('response_full', models.JSONField(blank=True, null=True)),
                ('result_short', models.CharField(blank=True, max_length=2000, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='newspaper.article')),
            ],
        ),
    ]
