# Generated by Django 5.2.7 on 2025-10-08 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0009_articleanalysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleAnalysisTool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
                ('system_prompt', models.TextField()),
                ('model', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleIndicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator', models.CharField(max_length=1000)),
                ('value', models.FloatField()),
                ('explanation', models.TextField()),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='newspaper.articleanalysis')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='indicators', to='newspaper.article')),
            ],
        ),
    ]
