# Generated by Django 5.2.7 on 2025-10-08 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0010_articleanalysistool_articleindicator'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleanalysistool',
            name='generates_indicators',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='articleanalysistool',
            name='indicators',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='articleanalysis',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analyses', to='newspaper.article'),
        ),
    ]
