# Generated by Django 5.2.7 on 2025-10-09 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0012_articleanalysistool_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewspaperScraper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scraper', models.TextField()),
                ('newspaper', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scrapers', to='newspaper.newspaper')),
                ('urls', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='newspaper.newspapersubpage')),
            ],
        ),
    ]
