# Generated by Django 5.2.7 on 2025-10-09 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0013_newspaperscraper'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newspaperscraper',
            name='urls',
        ),
        migrations.AddField(
            model_name='newspaperscraper',
            name='urls',
            field=models.ManyToManyField(to='newspaper.newspapersubpage'),
        ),
    ]
