# Generated by Django 5.2.7 on 2025-10-09 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0014_remove_newspaperscraper_urls_newspaperscraper_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspaperscraper',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
