# Generated by Django 5.2.7 on 2025-10-09 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0015_newspaperscraper_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
                ('description', models.TextField()),
                ('datatype', models.CharField(max_length=2000)),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('min_value_label', models.CharField(max_length=2000)),
                ('max_value_label', models.CharField(max_length=2000)),
            ],
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['scraped']},
        ),
        migrations.AlterModelOptions(
            name='articleanalysis',
            options={'ordering': ['analyzed']},
        ),
        migrations.RemoveField(
            model_name='articleanalysistool',
            name='indicators',
        ),
        migrations.AddField(
            model_name='articleanalysistool',
            name='indicators',
            field=models.ManyToManyField(to='newspaper.indicator'),
        ),
    ]
