# Generated by Django 5.2.7 on 2025-10-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0016_indicator_alter_article_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunDump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=2000)),
                ('run', models.TextField()),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='articleindicator',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='articleindicator',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
