# Generated by Django 5.2.7 on 2025-10-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0017_rundump_alter_articleindicator_explanation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rundump',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rundump',
            name='run',
            field=models.TextField(blank=True, null=True),
        ),
    ]
