# Generated by Django 5.2.7 on 2025-10-11 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0018_alter_rundump_end_alter_rundump_run'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='newspaper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='newspaper.newspaper'),
        ),
        migrations.CreateModel(
            name='NewspaperFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('fmt', models.CharField(max_length=200)),
                ('newspaper', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feeds', to='newspaper.newspaper')),
            ],
        ),
    ]
