# Generated by Django 5.2.7 on 2025-10-13 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0019_alter_article_newspaper_newspaperfeed'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleanalysistool',
            name='applies_to_content',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='articleanalysistool',
            name='applies_to_media',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='articleanalysistool',
            name='applies_to_title',
            field=models.BooleanField(default=False),
        ),
    ]
