# Generated by Django 5.2.7 on 2025-10-14 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0021_historicalnewspaperscraper'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-scraped']},
        ),
        migrations.AlterModelOptions(
            name='articleanalysis',
            options={'ordering': ['-analyzed']},
        ),
        migrations.AlterField(
            model_name='articleanalysis',
            name='result_short',
            field=models.TextField(blank=True, null=True),
        ),
    ]
