# Generated by Django 5.2.7 on 2025-10-14 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0022_alter_article_options_alter_articleanalysis_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleanalysistool',
            name='applies_to_summary',
            field=models.BooleanField(default=False),
        ),
    ]
