# Generated by Django 5.2.7 on 2025-10-14 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0023_articleanalysistool_applies_to_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rundump',
            name='action',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='rundump',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
