# Generated by Django 5.2.7 on 2025-10-14 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0024_alter_rundump_action_alter_rundump_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspaperscraper',
            name='urls',
            field=models.ManyToManyField(blank=True, null=True, to='newspaper.newspapersubpage'),
        ),
    ]
